### ISSUE TITLE
Add a method signature to ICodeFirstTypeProvider

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/delivery-sdk-net#101]
### Motivation

The Delivery API allows filtering of content items by their type. The SDK allows for specifying strong types that reflect content types of those items. The developer may request strongly typed items via

    var response = await DeliveryClient.GetItemsAsync<Article>(
        new EqualsFilter("system.type", "article"),
    );

To remove the burden of specifying the type twice (see above), we've [implemented](https://github.com/Kentico/delivery-sdk-net/pull/86/files) a `ContentTypeExtractor` class that uses reflection to automatically add the `EqualsFilter` in the background.

To get around using reflection, we could make our code generators also generate a dictionary inside of an `ICodeFirstTypeProvider` class that would return a codename for a particular `System.Type`.

### Howto

To make the above possible, add a `GetCodename` method to the [ICodeFirstTypeProvider](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/CodeFirst/ICodeFirstTypeProvider.cs) interface that accepts `System.Type` as a parameter.

Then, we could implement https://github.com/Kentico/cloud-generators-net/issues/61 .

**Comment by petrsvihlik** [comment]
done in https://github.com/Kentico/delivery-sdk-net/pull/121

**Comment by mcbeev** [comment]
@JanLenoch and @petrsvihlik I updated to the latest 6.0.0 release, and need to now implement the new `GetCodename` method, but I wanted to know if I have it correct. Stubbing it in looks like this: 

![image](https://user-images.githubusercontent.com/9918767/45931620-77960c80-bf3e-11e8-9b38-0430af9d95fe.png)

Now, I'm guessing that the code of that method wants the reverse of `GetType` to happen in `GetCodename` (convert the Type to a string representation)? But doesn't this seem like a lot of duplication? Or is the code gen tool updated to automatically do this for me now ?

Any guidance is appreciated.
Brian

**Comment by petrsvihlik** [comment]
Hey @mcbeev , yeah it's updated. See https://github.com/Kentico/delivery-sdk-net/releases/tag/6.0.0
