### ISSUE TITLE
Enrich link objects (ContentLink) with information about culture?

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/delivery-sdk-net#109]
**Motivation:** Currently, the [links](https://developer.kenticocloud.com/v1/reference#section-links-single-object-) in the Delivery responses do not contain the information about the culture of the linked content item. Just the `codename`, `type` and `url_slug`. We assume that developers do not need to render hyperlinks pointing to other culture variants other than the one the user has in their session.

**Question:** Would anyone need the information about the culture in the link object?

If so, we'd also add multi-language support to the [ContentLink](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/ContentLinks/ContentLink.cs) class, which is used by the [IContentLinkUrlResolver](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/ContentLinks/IContentLinkUrlResolver.cs) interface to produce links in the applications' UI. Classes like [link resolvers](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/ContentLinkUrlResolver/CustomContentLinkUrlResolver.cs) would be able to render links to different language variants.

**Comment by petrsvihlik** [comment]
apparently not
