### ISSUE TITLE
Circular Dependency is resulting in a overflow exception

### ISSUE THREAD

**Issue by micheltol** [Kentico/delivery-sdk-net#124]
### Brief bug description

I have a content model with a richtext component.  Based on this content model an user creates a content item in the KC portal. In the richtext component the user is able to refer to other content items. 
If the user makes the content item referencing itself (Circular Dependency) the KenticoCloud.Delivery  SDK is unable to deserialize the content item and throws an overflow exception .

### Repro steps
See above, Example repo is avilable @ https://github.com/micheltol/Kentico_CircularDependency

### Expected behavior
I would expect this would not be possible in the KC portal. 
Apperently there is an usecase for this behavior so I would expect the SDK to be able to deserialize the above mentioned situation.

### Test environment

 - Platform/OS: .NET Core 2.1
 - Version  Nuget KenticoCloud.Delivery : 5.0.0

**Comment by petrsvihlik** [comment]
Well spotted @micheltol !

**Comment by micheltol** [comment]
Hi @petrsvihlik,  
this issue was discovered while we were having a production issu. Because of that  it is important to us to solve this asap. I wouldn't mind to  to pick it up but could you point me in the right direction how to attack this issue?

**Comment by petrsvihlik** [comment]
I went ahead and debugged the issue. While doing that I also created a [fix](https://github.com/Kentico/delivery-sdk-net/pull/125). We'll release a new major version of the delivery sdk soon.
