### ISSUE TITLE
Do not throw an exception when a strong type is not provided

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#126]
_Originally submitted by: @micheltol in https://github.com/Kentico/cloud-generators-net/issues/67_

# A brief problem description

When a new content type is added to KC and a new item of that type is retrieved via Delivery API (either directly or as a modular item), such retrieval fails because of the type provider returning `null` as [the default `System.Type`](https://github.com/Kentico/cloud-boilerplate-net/blob/master/src/content/CloudBoilerplateNet/Models/ContentTypes/CustomTypeProvider.cs#L39) of such unknown content type, unless the new type provider (and models) are generated.

The code in question: https://github.com/Kentico/delivery-sdk-net/blob/7a368f54f462a8d2609a17cf2569d632bd7be14d/KenticoCloud.Delivery/CodeFirst/CodeFirstModelProvider.cs#L80

# What can we do if a type is not found?

1) Fail (current behavior)
2) Fill the property with `null`
3) Fill the property with `JObject` containing the raw data
4) Fill the property with an instance of `object` (I thing just `null` is better here)

# How should we fix the problem?
1) Choose one of the options above
2) Make the behavior configurable (via a bool / enum)

**Comment by hatalaef** [comment]
I'll take a look at this.
