### ISSUE TITLE
Structured Rich text rendering doesn't mention components

### ISSUE THREAD

**Issue by MartinaFarkasova** [Kentico/delivery-sdk-net#139]
https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering

With the release of the components, we should strive to mention them where it makes sense. Since the rendering should be the same for components as it is for the content items linked in RTE, we should add it to [the page](https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering).

_Internal reference: DEL-2083_

**Comment by CollierCZ** [comment]
I think this has been fixed since 22 October. Components are mentioned now.
