### ISSUE TITLE
Unable to retrieve boolean values

### ISSUE THREAD

**Issue by frederikstonge** [Kentico/delivery-sdk-net#144]
### Brief bug description

I was following this tutorial https://help.kenticocloud.com/define-content-structure/content-elements/using-multiple-choice-content-elements on how to use multiple choice checkbox to have a boolean value. However, i am unable to query it from my c# model, it is always false. I tried to use the control codename, and also the choice codename, but unsuccessfully.

### Repro steps

1. Follow this tutorial : https://help.kenticocloud.com/define-content-structure/content-elements/using-multiple-choice-content-elements
2. Create a c# model of your content type
3. Query an item from that content type
4. The boolean value is always false

**Comment by petrsvihlik** [comment]
Hi @frederikstonge , thanks for submitting this. I'm going to investigate it.

**Comment by petrsvihlik** [comment]
Hi @frederikstonge , it works fine:
1) Create a checkbox as described here: https://help.kenticocloud.com/define-content-structure/content-elements/using-multiple-choice-content-elements
2) Generate models using the [generator utility](https://github.com/Kentico/cloud-generators-net).
3) Create a partial class extending your model. Basically, wrap your `IEnumerable<MultipleChoiceOption>` property into a `bool` property.

```
public bool FlagBool
        {
            get
            {
                return Flag.FirstOrDefault() != null;
            }
        }
```

Here's the full code:
[BoolTest.zip](https://github.com/Kentico/delivery-sdk-net/files/2557587/BoolTest.zip)

The testing project contains two items, one with the flag enabled and the other with the flag disabled.

**Comment by petrsvihlik** [comment]
Feel free to reopen the issue or create a new one if you still have some questions.

**Comment by frederikstonge** [comment]
It works fine! Thank you!
