### ISSUE TITLE
Missing content model causes DeliveryClient to silently fail

### ISSUE THREAD

**Issue by ondrabus** [Kentico/delivery-sdk-net#145]
### Brief bug description

When a new content model is created in KC and there is no corresponding POCO in the app (therefore CustomTypeProvider does not recognize the model), DeliveryClient fails when returning content items that contain content items based on this model. It does not throw any exception, but returns with Items property containing null.
Problem is in InlineContentItemsProcessor.cs on line 69 -> inlineContentItem is null, therefore invoking GetType() will generate NullReferenceException. This exception is not propagated to the app, but silently ignored and DeliveryClient just returns null in DeliveryItemListingResponse.

### Repro steps

1. Generate POCO for KC content models
2. Add new content model in KC
3. Create content item that has a rich text editor. Add linked item based on the new content model
4. Get the new content item using DeliveryClient.GetItemsAsync
5. Items property of the result is null

### Expected behavior

I'd expect either null or exception. Not null of the whole Items property, but of the linked item that there is no POCO for.

### Test environment

 - Platform/OS: .NET 4.6

**Comment by petrsvihlik** [comment]
will be released in https://github.com/Kentico/delivery-sdk-net/releases/tag/9.0.0
