### ISSUE TITLE
Resolving inline items with IInlineContentItemsResolver is broken in v8

### ISSUE THREAD

**Issue by Enngage** [Kentico/delivery-sdk-net#146]
### Brief bug description

After upgrading SDK to v8, all non-default `IInlineContentItemsResolver` registered using the `DeliveryClientBuilder` with `WithInlineContentItemsResolver` such as:

```
    public class InlineCodeResolver : IInlineContentItemsResolver<CodeBlock>
    {
        public string Resolve(ResolvedContentItemData<CodeBlock> data)
        {
            return
                $"Do something";
        }
    }

```
` .WithInlineContentItemsResolver(new InlineCodeResolver())`

Are not resolved and never called. These resolvers worked in previous versions as expected.

The only resolver that gets called is the default one registered with `object`. Strangely, default resolver gets strongly typed items as I expect so I can do something like this as a workaround:

```
public class DefaultContentItemResolver : IInlineContentItemsResolver<object>
    {
        public string Resolve(ResolvedContentItemData<object> data)
        {
            if (data.Item is CodeBlock codeBlock)
            {
                return
                    $"Do something";
            }
            return "Content not available.";
        }
    }
```

### Expected behavior

Registered resolvers should be called instead of falling back to default one.

**Comment by petrsvihlik** [comment]
you can check out #147 , if you want...and possibly add some review comments if you like

**Comment by petrsvihlik** [comment]
will be released in https://github.com/Kentico/delivery-sdk-net/releases/tag/9.0.0
