### ISSUE TITLE
Custom default inline content items resolver registered through builder is not used

### ISSUE THREAD

**Issue by matus12** [Kentico/delivery-sdk-net#149]
### Brief bug description

When I register a custom default inline content items resolver and a resolver for UnretrievedContentItems through the DeliveryClientBuilder, the default implementation of the resolvers is used in the InlineContentItemsProcessor instead of the custom ones.

### Expected behavior

When I register a custom default inline content items resolver or the resolver for unretrieved content items DeliveryClientBuilder, they are used in the InlineContentItemsProcessor.

**Comment by petrsvihlik** [comment]
will be released in https://github.com/Kentico/delivery-sdk-net/releases/tag/9.0.0
