### ISSUE TITLE
Inline content resolver in v9 has unnecessary wrapping

### ISSUE THREAD

**Issue by Enngage** [Kentico/delivery-sdk-net#153]
This related to https://github.com/Kentico/delivery-sdk-net/issues/146 (which GitHub cant display for some reason). 

Basically, I have inline resolver defined as

```
public class DefaultContentItemResolver : IInlineContentItemsResolver<object>
    {

        public string Resolve(ResolvedContentItemData<object> data)
        {
            if (data.Item is ResolvedContentItemData<object> itemWrapper)
            {
                if (itemWrapper.Item is InfoBox infoBox)
                {
                    return $"<div>{infoBox.Content}</div>";
                }

                if (itemWrapper.Item is CodeBlock codeBlock)
                {
                    return
                        $"<pre><code class=\"language-{codeBlock.AvailableLanguagesLanguage?.FirstOrDefault()?.Codename.ToLower().Trim()}\">" +
                            $"{System.Web.HttpUtility.HtmlEncode(codeBlock.Code)?.Trim()}" +
                        $"</code></pre>";
                }
            }

            return "Content not available.";
        }
    }
```

Main problem I have is with the `Resolve(ResolvedContentItemData<object> data)` because I would expect the `Item` inside to be of resolved content item type (e.g. `CodeBlock` or `InfoBox` in my case), but its type is another `ResolvedContentItemData<object>` which is why I have to do:

```
if (data.Item is ResolvedContentItemData<object> itemWrapper)
    {
         if (itemWrapper.Item is InfoBox infoBox)
         {
         }
}
```

**Comment by PetrSvirak** [comment]
Thank you for spotting this one. You are right that `data.Item` described in the code above should carry either `CodeBlock` or `InfoBox` or any other content type directly (definitely not another&nbsp;`ResolvedContentItemData<>`).
I would go even a bit further and state that `ResolvedContentItemData` class itself is redundant and we should actually remove it for good. We will further investigate the issue, stay tuned.

Meanwhile, I have noticed one thing in your scenario that I'm not sure whether I understand correctly:

Based on my understanding, there will always be a `DefaultContentItemResolver` that will only accept Item in a form of an `object` – this resolver is kind of a last resort for resolving inline content items. 

If I want strongly typed resolvers, I just register some. In the case above, it would be one for `InfoBox` and another for `CodeBlock`:

> First,  I would implement two resolvers

```csharp
public class InfoBoxContentItemResolver : IInlineContentItemsResolver<InfoBox>
{
    public string Resolve(ResolvedContentItemData<InfoBox> data)
       => $"<div>{infoBox.Content}</div>";
}

public class CodeBlockContentItemResolver : IInlineContentItemsResolver<CodeBlock >
{
    public string Resolve(ResolvedContentItemData<CodeBlock> data)
       => $"<pre><code class=\"language-{codeBlock.AvailableLanguagesLanguage?.FirstOrDefault()?.Codename.ToLower().Trim()}\">" +
          $"{System.Web.HttpUtility.HtmlEncode(codeBlock.Code)?.Trim()}" +
          $"</code></pre>";
}
```

> Then, I would register resolvers instead of the default one:
>  Either using DI:
```csharp
services
    .AddDeliveryInlineContentItemsResolver<InfoBox, InfoBoxContentItemResolver>();
    .AddDeliveryInlineContentItemsResolver<CodeBlock, CodeBlockContentItemResolver>();
    //instead of: .AddDeliveryInlineContentItemsResolver<object, DefaultContentItemResolver>();
    .AddDeliveryClient(Configuration);
```

> Or using a builder:

```csharp
IDeliveryClient client = DeliveryClientBuilder
    .WithProjectId(/*ProjectId*/)
    .WithInlineContentItemsResolver(new InfoBoxContentItemResolver())
    .WithInlineContentItemsResolver(new CodeBlockContentItemResolver())
    //instead of: .WithInlineContentItemsResolver(new DefaultContentItemResolver())
    .Build();
```

While your sample above perfectly illustrates the issue at hand, I'm wondering whether there is any particular pitfall that discourages you from declaring multiple strongly types resolvers for your inline content items – we might be able to tinker resolvers a bit more to fit your needs even better.

Please note, that the code that I described above does not prevent you from declaring a resolver for unhandled content items and registering it for `object` content items (aka default "fallback" resolver). Something along:
```csharp
public class DefaultContentItemResolver : IInlineContentItemsResolver<object>
{
    public string Resolve(ResolvedContentItemData<CodeBlock> data)
       => "Content not available.";
}

// either DI registration
services
    …
    .AddDeliveryInlineContentItemsResolver<object, DefaultContentItemResolver>();
    …
    .AddDeliveryClient(Configuration);

// or builder registration
IDeliveryClient client = DeliveryClientBuilder
    …
    .WithInlineContentItemsResolver(new DefaultContentItemResolver())
    …
    .Build();
```
There is still the [`ReplaceWithWarningAboutRegistrationResolver`](https://github.com/Kentico/delivery-sdk-net/blob/0af64b0b5345a4dc4e62b55b907ed67b9ef68d31/KenticoCloud.Delivery/InlineContentItems/ReplaceWithWarningAboutRegistrationResolver.cs) that is [registered](https://github.com/Kentico/delivery-sdk-net/blob/0af64b0b5345a4dc4e62b55b907ed67b9ef68d31/KenticoCloud.Delivery/Extensions/ServiceCollectionExtensions.cs#L111) by default and might be sufficient for, hopefelly most, corner cases – so creating a weakly-typed resolver might not be always necessary.

**Comment by Enngage** [comment]
Thanks for the long reply :-) I initially used dedicated content item resolvers, but there was a bug in v8 where it didn't work at all (the issue I referenced at the top) so I had to use the generic `object` resolver and I actually like it more as it makes code clearer and easier to use. Sure, if you had more complex logic it might be worth separating to multiple classes/files

**Comment by petrsvihlik** [comment]
So, is there space for improvement or is this issue not valid?

**Comment by Enngage** [comment]
This issue is valid as @petrpyszko mentioned in his response.
