### ISSUE TITLE
CodeFirstModelProvider shouldn't set null for collections

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/delivery-sdk-net#17]
It should be consistent with `ContentItem`.

With `ContentItem.GetModularContent("related_articles")` I get an empty collection if there is no modular content. With custom Strongly Typed model, I get a null value.

It forces me to use null check in my MVC views
```
foreach(var article in Model.GetModularContent("related_articles"))
{ ... }

// vs.

if (Model.RelatedArticles != null) 
{
    foreach(var article in Model.RelatedArticles)) { ... }
}
```

IMO it's safer to return an empty collection. Developers won't see so many exceptions on their websites 🙂

**Comment by petrsvihlik** [comment]
good point, we should align the two together

**Comment by petrsvihlik** [comment]
fixed in https://github.com/Kentico/delivery-sdk-net/pull/29
