### ISSUE TITLE
Replace usage of the sample project in tests with mocked responses

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#22]
Currently, the [`DeliveryClientTests`](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery.Tests/DeliveryClientTests.cs) depends on two sample projects in Kentico Cloud ("975bf280-fd91-488c-994c-2f04416e5ee3" and "e1167a11-75af-4a08-ad84-0582b463b010").

- [ ] We'd like to remove that dependency and use fake responses instead. Ideally, it should be done by mocking the httpclient (via moq or fakeiteasy).
- [ ] add test for #43 (`item.AssetField.First().Description`)

**Comment by charithsoori** [comment]
Hi @petrsvihlik ,
I would like to pick this task. I hope this task will be a good starting point for me to delivery-sdk-net .

**Comment by petrsvihlik** [comment]
Yes, indeed it's a good task to start with. Thanks for a great job! I've added a follow-up task https://github.com/Kentico/delivery-sdk-net/issues/84.

**Comment by charithsoori** [comment]
Great . I'll start working on  #84

**Comment by petrsvihlik** [comment]
fixed in #83
