### ISSUE TITLE
Get rid of build-time conditions

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#39]
Convert this:

```
 #if (DEBUG && NET45)
        private string PRODUCTION_ENDPOINT = ConfigurationManager.AppSettings["ProductionEndpoint"] ?? "https://deliver.kenticocloud.com/{0}";
        private string PREVIEW_ENDPOINT = ConfigurationManager.AppSettings["PreviewEndpoint"] ?? "https://preview-deliver.kenticocloud.com/{0}";
        #else
        private const string PRODUCTION_ENDPOINT = "https://deliver.kenticocloud.com/{0}";
        private const string PREVIEW_ENDPOINT = "https://preview-deliver.kenticocloud.com/{0}";
        #endif
```
in [DeliveryEndpointUrlBuilder](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/DeliveryEndpointUrlBuilder.cs) to use [ASP.NET Core Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration).

Custom class that can read appSettings from web.config needs to be implemented.

**Comment by jjarnot-vimanet** [comment]
Hi Petr,

Please take a look at code below and let me know if this is what you want.

`public class ConfigManager
{
    #if (!NET45)
    static IConfigurationRoot configuration;

    static ConfigManager()
    {
        var builder = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json");

        configuration = builder.Build();
    }
    #endif

    private static string GetProperty(string name)
    {
        #if (NET45)
            return ConfigurationManager.AppSettings[name];
        #else
            return configuration[name];
        #endif
    }

    public static string PRODUCTION_ENDPOINT
    {
        get
        {
            return GetProperty("ProductionEndpoint");
        }
    }

    public static string PREVIEW_ENDPOINT
    {
        get
        {
            return GetProperty("PreviewEndpoint");
        }
    }
}`

Thanks!

**Comment by petrsvihlik** [comment]
What I meant was:

- `PRODUCTION_ENDPOINT` and `PREVIEW_ENDPOINT` should read from the `Configuration` object...e.g. using `GetValue` - see the docu: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration#getvalue -> `Configuration.GetValue("PreviewEndpoint", "https://preview-deliver.kenticocloud.com/{0}")`

- the `Configuration` object should be filled with a custom configuration provider - see the implementation of `LegacyConfigurationProvider` in http://benfoster.io/blog/net-core-configuration-legacy-projects -> this is exactly what we want

This way:
- the NET45-specific functionality would be isolated in a separate class 
- the code would rely on the new .net core configuration model
  - which means it could be easily extended by adding more providers etc.
    - which is btw exactly what we should do in a follow up story and let the deliveryclient read from the configuration object (the consumer then could just pass a configuration section and wouldn't have to provider projectid and preview api key) #54

**Comment by jjarnot-vimanet** [comment]
Hi @petrsvihlik!

Can you please assign this issue to me.
I've got solution for this and want to create pull request.

Thanks!

**Comment by petrsvihlik** [comment]
Awesome! :) Item assigned...

**Comment by jjarnot-vimanet** [comment]
Pull request created.
Thanks!
