### ISSUE TITLE
Unit tests vs. integration tests?

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/delivery-sdk-net#41]
Do we want/need to expand the testing to unit tests? The current tests look like integration tests to me as they rely on at least two different projects (which could get modified) and requires the deliver endpoint to be accessible and available.

**Comment by petrsvihlik** [comment]
You are right. Currently, the tests are integration tests. We'd like to get rid of the dependency on the live KC service.
See https://github.com/Kentico/delivery-sdk-net/issues/22 for more details.
