### ISSUE TITLE
Let the DeliveryClient be initialized by passing a configuration section

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#54]
We should let the `DeliveryClient` (and its subclasses) read from a configuration object . The consumer would have the option of passing a configuration object and not having to provide projectid and preview api key explicitly through the constructor.

This story should lead to a better support of DI scenarios, better separation of concerns (e.g. `DeliveryEndpointUrlBuilder` should not know anything about where its settings come from) and ability to control settings on an application level.

Suggested changes:
- introduce a new class `DeliveryOptions` with 4 properties (ProductionEndpoint, PreviewEndpoint, ProjectId, PreviewApiKey) - the first two will have their default values set (similarly to [MyOptions](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration))
- `DeliveryEndpointUrlBuilder` 
  - will have a new constructor accepting `IOptions<DeliveryOptions> options`
  - will internally use the `IOptions<DeliveryOptions>` object
  - the old constructors should construct the `IOptions<DeliveryOptions>` object as well
  - `DeliveryClient` will use the new constructor with `IOptions<DeliveryOptions>` object to construct the `DeliveryEndpointUrlBuilder`
  - the constructors should be chained, if possible (`:this(...)`)
  - it will no longer be possible to override `ProductionEndpoint` and `PreviewEndpoint` when using the old constructors (shouldn't be a breaking change for anyone)...(it will still be possible by using the new constructor)
- `DeliveryClient`
  - will have a new constructor accepting `IOptions<DeliveryOptions> options`
  - will internally use the `IOptions<DeliveryOptions>` object
  - the old constructors should construct the `IOptions<DeliveryOptions>` object
- the `NET45ConfigurationProvider` (#57)
  - will be converted to a class that returns an `IOptions<DeliveryOptions>` object (`
            IOptions<DeliveryOptions> a = new OptionsManager<DeliveryOptions>(new List<IConfigureOptions<DeliveryOptions>>());
            return a;`)
  - this is a **breaking change** for Kentico who'll have to call this method prior instantiating the `DeliveryClient` using the new constructor (only in NET45)

- It may be possible to [avoid](https://andrewlock.net/reloading-strongly-typed-options-in-asp-net-core-1-1-0/) the `IOptions` wrapper.
- Follow up story: #59
Resources: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration

**Comment by petrsvihlik** [comment]
@kentico-jiris @alesk-kentico are you ok with the breaking change (this will only affect Kentico)

**Comment by alesk-kentico** [comment]
The proposed changes look good and the reasons are sound. Just out of curiosity, how can you be sure that these changes will only affect Kentico?

**Comment by petrsvihlik** [comment]
Well, one can never be 100% sure but since currently it's possible to configure only ProductionEndpoint and PreviewEndpoint (and that only in NET45 via web.conifg) I don't see why anyone would want to change these URLs, especially if the two settings are undocumented.

**Comment by alesk-kentico** [comment]
Makes sense. Godspeed, then :)

**Comment by petrsvihlik** [comment]
@jjarnot-vimanet Before we close this issue, could you please create a new [wiki page](https://github.com/Kentico/delivery-sdk-net/wiki) and document how developers can use DI to configure the client?

- it should contain a short [code example](https://github.com/Kentico/delivery-sdk-net/pull/60#issuecomment-316341013) of the Startup class
- example appsettings.json config
- link to MS docu about configuration

Thanks!

Btw - I've created a follow-up issue that, I believe, will be the final one related to instantiation of the DeliveryClient - https://github.com/Kentico/delivery-sdk-net/issues/63. Please let me know, if it makes sense.

**Comment by jjarnot-vimanet** [comment]
Ok. I will create new wiki page with info you specified.

**Comment by petrsvihlik** [comment]
thx @jjarnot-vimanet for writing down the articles!

https://github.com/Kentico/delivery-sdk-net/wiki/Loading-DeliveryClient-settings-from-web.config
https://github.com/Kentico/delivery-sdk-net/wiki/Using-the-ASP.NET-Core-Configuration-API-and-DI-to-Instantiate-the-DeliveryClient

**Comment by jjarnot-vimanet** [comment]
I'm glad I could help.
Thanks!
