### ISSUE TITLE
GetItemsAsync<T> should generate type filter automatically

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#79]
Strongly typed methods like `GetItemsAsync<T>` should generate and apply a type [filter](https://github.com/Kentico/delivery-sdk-net/tree/master/KenticoCloud.Delivery/QueryParameters) automatically.

`T` contains codename of the content type (see e.g. [`Cafe.cs`](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/Models/ContentTypes/Cafe.cs)) so it should be no problem.

**Comment by daemoon** [comment]
I'll take a crack at it, if noone is already.

**Comment by petrsvihlik** [comment]
Solved in #86
