### ISSUE TITLE
Depth=0 vs Depth=1 & modular content

### ISSUE THREAD

**Issue by strizr** [Kentico/delivery-sdk-net#81]
While requesting our blog post content items with `depth=0` and selecting also top-level modular content author i get this response: 
![depth-bug](https://user-images.githubusercontent.com/25004216/30809818-63d9a62e-a203-11e7-9d08-ed3103de938c.png)
You can see, that the "author" modular content is present in the json response. However, when i use 
`item.GetModularContent("author")`, `null `is returned. 
When setting `depth=1` , the same exact json response is returned; however, `item.GetModularContent("author")` returns expected values. 
I am really confused, is this really the intended behavior? I thought the depth parameter should limit the amount of data I'm gonna receive (also, i can easily avoid the SDK and get my author data from the response directly).

**Comment by strizr** [comment]
The docs reads:
>  If you need to exclude all modular content from the response, set the parameter to 0
So this is probably a bug in the delivery API, if the SDK is calling it correctly. Can somebody verify?

**Comment by petrsvihlik** [comment]
@strizr we'll take a look. could you possibly share the request URLs?

**Comment by strizr** [comment]
Looks like a bug in delivery API:
`https://deliver.kenticocloud.com/4e9bdd7a-2db8-4c33-a13a-0c368ec2f108/items?system.type=blog_post&depth=0&order=elements.date%5Bdesc%5D&elements=title%2Cdate%2Cauthor%2Cbody%2Ctopic%2Curl_slug&limit=1`

**Comment by petrsvihlik** [comment]
Nope, it works perfectly fine. If you set depth=0 then you get:

```
"items": [
    {
...
"author": {
          "type": "modular_content",
          "name": "Author",
          "value": [
            "bryan_soltis"
          ]
        }
...
}],
"modular_content": {}
```

However, if you set depth=1, the `modular_content` changes to:
```
"modular_content": {
    "bryan_soltis": {
      "system": {
        "id": "d92a44e2-2d75-4606-b8f7-e3c4a02dd6b2",
        "name": "Bryan Soltis",
        "codename": "bryan_soltis",
        "language": "default",
        "type": "author",
        "sitemap_locations": [],
        "last_modified": "2017-02-24T11:09:55.9458096Z"
      },
      "elements": {}
    }
  },
```

So basically the difference is that in the first response you get just the codename of the modular content and in the second response you get modular content data as well. This way you can resolve the modular content field.

**Comment by petrsvihlik** [comment]
You would have noticed this behavior more easily if you took the strongly typed approach: https://github.com/Kentico/delivery-sdk-net/wiki/Working-with-strongly-typed-models-(aka-Code-First-approach)

**Comment by strizr** [comment]
Thank you for the clarification, you are the best! I was looking into the .NET object and not to the json response itself.
