### ISSUE TITLE
Add mocked responses to the rest of the unit tests

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#84]
Similarly to #22 (PR #83), add fixtures to `ContentLinkResolverTests` and `ValueConverterTests`.

**Comment by charithsoori** [comment]
Starting to work in.

**Comment by petrsvihlik** [comment]
great! if you accept the invitation i've just sent you, i can assign the issue directly to you

**Comment by charithsoori** [comment]
Ok . Now you Assign.

**Comment by petrsvihlik** [comment]
thank you @charithsoori !

if you're looking for another one to finish your hacktoberfest run, try: https://github.com/Kentico/cloud-boilerplate-net/issues/39

i've also took the liberty of adding you to our [wall of fame](https://github.com/Kentico/delivery-sdk-net/blob/master/README.md#wall-of-fame)

**Comment by charithsoori** [comment]
@petrsvihlik Thank you very much for tagging me in wall of fame. Sure I'll start to work on this task soon. I am planning to contribute to .net core projects for some time and Kentico easily caught my eye.

**Comment by petrsvihlik** [comment]
fixed in #85
