### ISSUE TITLE
Support for ReactiveX programming

### ISSUE THREAD

**Issue by Enngage** [Kentico/delivery-sdk-net#88]
Are there any plans to support [ReactiveX](http://reactivex.io/) and their [Rx.NET ](https://github.com/Reactive-Extensions/Rx.NET) extension? 

I feel like this could be a nice addition to the SDK as it would make working with (especially multiple) asynchronous operations much easier. Especially it would help with cancelling, chaining, retrying and error handling of the http requests that are made to Kentico Cloud. 

The highest benefit would receive UI heavy applications (i.e. desktop apps), but it would be useful for web as well.

**Comment by petrsvihlik** [comment]
It sounds like an interesting opportunity. Just a few observations from what I've learned about RX so far:
- If it's supposed to make a UI more responsive, RX only makes sense for apps that run on the same machine as the code pulling the data from the Delivery API - e.g. Windows/UWP apps, etc. AFAIK, the benefit of RX would be lost when the data is about to be transferred by a single HTTP response to a client.
- Another use case would be apps without a UI that periodically (post)process data. E.g. they could build search indexes, send notification or whatever...(could we perhaps somehow observe incoming webhooks?)
- We [shouldn't](http://www.introtorx.com/content/v1.0.10621.0/01_WhyRx.html) make the SDK reactive just for the sake of it

Could you please suggest a design?

Some nice resources:
- https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Rx.NET/Samples/HOL/Rx%20HOL%20.NET%20C%23.pdf

**Comment by JanLenoch** [comment]
I've done three spikes on the topic:
* Convert async IO calls into Rx observables in an MVC app
* Listen to web hooks in an MVC app and make the web hooks an observable stream
* Implement Rx in an UWP app

### Convert IO calls into Rx
In MVC, the observables don't bring much value and add significant overhead:

        public async Task<ViewResult> Index()
        {
            // Use the stock factory method to make the async call an observable.
            var responseObservable = Observable.FromAsync(() => DeliveryClient.GetItemsAsync<Article>(
                new LimitParameter(3),
            ));

            return View((await responseObservable.ToTask()).Items);
        }

Returning the MVC `ActionResult` cannot be made an observer of the `responseObservable`. It needs to be converted back to a `Task` which is slightly clumsy.

### Listen to observable webhooks
Very practical use case. Once a webhook notification arrives, there can be multiple observers listening to it. The only downside is that in .NET, Rx came a bit late to the party, and, an `event` needs to be defined anyways.

    public class WebhookObservableProvider : IWebhookObservableProvider
    {
        public event EventHandler<WebhookNotificationEventArgs> WebhookNotification;

        public void RaiseWebhookNotification(IdentifierSet identifierSet)
        {
            if (WebhookNotification != null && identifierSet != null)
            {
                WebhookNotification.Invoke(this, new WebhookNotificationEventArgs(identifierSet));
            }
        }

        public IObservable<WebhookNotificationEventArgs> GetObservable()
        {
            return Observable.FromEventPattern<WebhookNotificationEventArgs>(this, nameof(WebhookNotification)).Select(e => e.EventArgs);
        }
    }

Apart from minimal performance costs of the `event`, there is no real downside of having a Rx-enabled webhook controller and its corresponding observable provider. I'd like to bring these to our boilerplate project soon.

### Rx in an UWP app
Rx is most useful in native apps. Although in UWP, the "legacy" of .NET events still makes the implementation of Rx a bit cumbersome, it works. Specifically, UWP data-bound UI controls rely in the `INotifyPropertyChanged` interface based on events, not observables.

    public class DeliveryViewModel : INotifyPropertyChanged
    {
        private string _searchQuery;
        private List<string> _results;

        public string SearchQuery
        {
            get { return _searchQuery; }
            set
            {
                _searchQuery = value;
                RaisePropertyChanged(nameof(SearchQuery));
            }
        }

        public List<string> Results
        {
            get { return _results; }
            set
            {
                _results = value;
                RaisePropertyChanged(nameof(Results));
            }
        }

        public DeliveryClient DeliveryClient { get; set; }
        public event PropertyChangedEventHandler PropertyChanged;

        public DeliveryViewModel()
        {
            DeliveryClient = new DeliveryClient("975bf280-fd91-488c-994c-2f04416e5ee3");

            var searchQueryObservable = Observable.FromEventPattern<PropertyChangedEventArgs>(this, nameof(PropertyChanged))
                .Select(e => ((DeliveryViewModel)e.Sender).SearchQuery)
                .DistinctUntilChanged()
                .Throttle(TimeSpan.FromSeconds(1));

            // Option 1: Directly populate the Results via an ordinary async/await call to DeliveryClient.
            //var searchQuerySubscription = searchQueryObservable.Subscribe(async searchQuery => Results = (await DeliveryClient.GetItemsAsync<Article>(new ContainsFilter("elements.persona", searchQuery))).Items.Select(i => i.Title).ToList());

            // Option 2: Make each call to the DeliveryClient also an observable (with that same async call as an observer).
            var resultsObservable = searchQueryObservable.SelectMany(async searchQuery => (await DeliveryClient.GetItemsAsync<Article>(new ContainsFilter("elements.personas", searchQuery), new ElementsParameter("title"))).Items.Select(i => i.Title).ToList());

            // Make the observer code execute through the UI thread's dispatcher and clear the Results upon each (distinct and throttled) keystroke in the text box.
            searchQueryObservable.ObserveOn(SynchronizationContext.Current).Subscribe(searchQuery => Results = null);

            // Do the same thread synchronization for the resultsObservable and populate the Results upon each response from Kentico Cloud.
            resultsObservable.ObserveOn(SynchronizationContext.Current).Subscribe(results => Results = results);
        }

        private void RaisePropertyChanged(string propertyName)
        {
            if (!string.IsNullOrEmpty(propertyName))
            {
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

It seems to be better to add Rx support to the boilerplate, rather than the SDK, since with our own code in the SDK, we wouldn't bring much value as opposed to the stock factory methods like `Observable.FromAsync()`. What do you guys think?

**Comment by petrsvihlik** [comment]
ok, let's:
- clean up the [code](https://github.com/Kentico/cloud-articles-examples/tree/rx/uwp-rx), 
- keep only the uwp sample, delete the rest 
- and merge it to master.

We'll use the UWP app as a foundation for a blogpost.

**Comment by Enngage** [comment]
I don't think there would be any overhead for developers. Consider following example:

```
public async Task<ActionResult> Index(){    
    return await kenticoCloud.GetItems()                     
          .Select(response=> new ItemsModel(response))                     
         .ToActionResult(View);}
```

Thats all you would essentially need to do if the `kenticoCloud.GetItems()` returned an observable.

Returning Observables give developers ability to easily implement retry functionality, cancellation, nested queries (i.e. get items from KC based on another result of KC call) and more. 

Unlike other languages, there is a solid support by .NET for async calls and thats what probably most developers are using, but giving them ability to use Observables would be a _nice touch_ (especially if they would be developing other then web applications).

**Comment by JanLenoch** [comment]
As per previous comments:

* cleaned up,
* kept only the UWP sample,
* merged to [master](https://github.com/Kentico/cloud-articles-examples/tree/master/uwp-rx).
