### ISSUE TITLE
Add roslyn analyzers & fix potential issues

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-net#92]
### Motivation

We use tests to prevent bugs. To make test code as reliable as it gets, the XUnit team has leveraged Roslyn to create [XUnit Analyzers](https://www.nuget.org/packages/xunit.analyzers). It is a NuGet package that will make Visual Studio warn about issues that were not visible before.

### Howto

- [ ] [Add](https://github.com/xunit/xunit.analyzers#how-to-install) `xunit.analyzers` to the test project
- [ ] Fix found issues

### Resources

http://davidpine.net/blog/xunit-powered-by-roslyn/

**Comment by vit-svoboda** [comment]
According to that [add](https://github.com/xunit/xunit.analyzers#how-to-install) page, you don't need to explicitly reference the analyzers since xunit 2.3.0, what is lower than we're already using. Haven't found no issues either.

**Comment by petrsvihlik** [comment]
I can confirm that. I already tested it in other projects. Thx @vit-svoboda
